

export const PetImages = {

    // "actionPet": [
    //     require('../assets/images/game-images/animations/pet_1_2.gif'),
    //     require('../assets/images/game-images/animations/pet_2_2.gif')
    // ],
    // "egg": [
    //     require('../assets/images/game-images/pets/egg_1.png'),
    //     require('../assets/images/game-images/pets/egg_2.png'),
    //     require('../assets/images/game-images/pets/egg_3.png')
    // ],
    "egg": [
        require('../assets/images/game-images/eggs/egg red.png'),
        require('../assets/images/game-images/eggs/egg light red.png'),
        require('../assets/images/game-images/eggs/egg orange.png'),
        require('../assets/images/game-images/eggs/egg yellow.png'),
        require('../assets/images/game-images/eggs/egg lime green.png'),
        require('../assets/images/game-images/eggs/egg green.png'),
        require('../assets/images/game-images/eggs/egg turqouise.png'),
        require('../assets/images/game-images/eggs/egg lightest blue.png'),
        require('../assets/images/game-images/eggs/egg light blue.png'),
        require('../assets/images/game-images/eggs/egg dark purple.png'),
        require('../assets/images/game-images/eggs/egg purple.png'),
        require('../assets/images/game-images/eggs/egg dark magenta.png'),
        require('../assets/images/game-images/eggs/egg pink.png'),
    ],
    //require('../assets/images/game-images/eggs/egg grey.png')
    // "egg_broken": [
    //     require('../assets/images/game-images/pets/egg_1_broken.png'),
    //     require('../assets/images/game-images/pets/egg_2_broken.png'),
    //     require('../assets/images/game-images/pets/egg_3_broken.png')
    // ],
    "egg_wiggle": [
        require('../assets/images/game-images/eggs/egg red_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg light red_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg orange_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg yellow_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg lime green_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg green_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg turqouise_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg lightest blue_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg light blue_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg dark purple_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg purple_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg dark magenta_sparkle.gif'),
        require('../assets/images/game-images/eggs/egg pink_sparkle.gif'),

    ],
    // "pet_placeholder": [
    //     require('../assets/images/game-images/pets/placeholders/pet_1.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_2.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_3.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_4.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_5.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_6.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_7.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_8.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_9.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_10.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_11.png'),
    //     require('../assets/images/game-images/pets/placeholders/pet_12.png'),
    // ],
    "pet_placeholder": [
        require('../assets/images/game-images/Silhouettes/hidden_ally1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_ally2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_ally3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_ally4.png'),
        require('../assets/images/game-images/Silhouettes/hidden_amour1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_amour2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_amour3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_amour4.png'),
        require('../assets/images/game-images/Silhouettes/hidden_amour5.png'),
        require('../assets/images/game-images/Silhouettes/hidden_cro1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_fia1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gato1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gato2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gato3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gato4.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gato5.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gato6.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gato7.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gray1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gray2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_gray3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_jd1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_jig1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_julia1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_julia2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_mima1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_moralle1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_moralle2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_moralle3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_quail1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_quo1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_quo2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_quo3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_silk1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_silk2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_silk3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_slacky1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_slacky2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy4.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy5.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy6.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy7.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy8.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy9.png'),
        require('../assets/images/game-images/Silhouettes/hidden_splishy10.png'),
        require('../assets/images/game-images/Silhouettes/hidden_tono1.png'),
        require('../assets/images/game-images/Silhouettes/hidden_tono2.png'),
        require('../assets/images/game-images/Silhouettes/hidden_tono3.png'),
        require('../assets/images/game-images/Silhouettes/hidden_tpop1.png'),
    ],
    "pet": [
        require('../assets/images/game-images/pets/ally1.png'),
        require('../assets/images/game-images/pets/ally2.png'),
        require('../assets/images/game-images/pets/ally3.png'),
        require('../assets/images/game-images/pets/ally4.png'),
        require('../assets/images/game-images/pets/amour1.png'),
        require('../assets/images/game-images/pets/amour2.png'),
        require('../assets/images/game-images/pets/amour3.png'),
        require('../assets/images/game-images/pets/amour4.png'),
        require('../assets/images/game-images/pets/amour5.png'),
        require('../assets/images/game-images/pets/cro1.png'),
        require('../assets/images/game-images/pets/fia1.png'),
        require('../assets/images/game-images/pets/gato1.png'),
        require('../assets/images/game-images/pets/gato2.png'),
        require('../assets/images/game-images/pets/gato3.png'),
        require('../assets/images/game-images/pets/gato4.png'),
        require('../assets/images/game-images/pets/gato5.png'),
        require('../assets/images/game-images/pets/gato6.png'),
        require('../assets/images/game-images/pets/gato7.png'),
        require('../assets/images/game-images/pets/gray1.png'),
        require('../assets/images/game-images/pets/gray2.png'),
        require('../assets/images/game-images/pets/gray3.png'),
        require('../assets/images/game-images/pets/jd1.png'),
        require('../assets/images/game-images/pets/jig1.png'),
        require('../assets/images/game-images/pets/julia1.png'),
        require('../assets/images/game-images/pets/julia2.png'),
        require('../assets/images/game-images/pets/mima1.png'),
        require('../assets/images/game-images/pets/moralle1.png'),
        require('../assets/images/game-images/pets/moralle2.png'),
        require('../assets/images/game-images/pets/moralle3.png'),
        require('../assets/images/game-images/pets/quail1.png'),
        require('../assets/images/game-images/pets/quo1.png'),
        require('../assets/images/game-images/pets/quo2.png'),
        require('../assets/images/game-images/pets/quo3.png'),
        require('../assets/images/game-images/pets/silk1.png'),
        require('../assets/images/game-images/pets/silk2.png'),
        require('../assets/images/game-images/pets/silk3.png'),
        require('../assets/images/game-images/pets/slacky1.png'),
        require('../assets/images/game-images/pets/slacky2.png'),
        require('../assets/images/game-images/pets/splishy1.png'),
        require('../assets/images/game-images/pets/splishy2.png'),
        require('../assets/images/game-images/pets/splishy3.png'),
        require('../assets/images/game-images/pets/splishy4.png'),
        require('../assets/images/game-images/pets/splishy5.png'),
        require('../assets/images/game-images/pets/splishy6.png'),
        require('../assets/images/game-images/pets/splishy7.png'),
        require('../assets/images/game-images/pets/splishy8.png'),
        require('../assets/images/game-images/pets/splishy9.png'),
        require('../assets/images/game-images/pets/splishy10.png'),
        require('../assets/images/game-images/pets/tono1.png'),
        require('../assets/images/game-images/pets/tono2.png'),
        require('../assets/images/game-images/pets/tono3.png'),
        require('../assets/images/game-images/pets/tpop1.png'),
    ],
    "actionPet": [
        require('../assets/images/game-images/pets/ally1.gif'),
        require('../assets/images/game-images/pets/ally2.gif'),
        require('../assets/images/game-images/pets/ally3.gif'),
        require('../assets/images/game-images/pets/ally4.gif'),
        require('../assets/images/game-images/pets/amour1.gif'),
        require('../assets/images/game-images/pets/amour2.gif'),
        require('../assets/images/game-images/pets/amour3.gif'),
        require('../assets/images/game-images/pets/amour4.gif'),
        require('../assets/images/game-images/pets/amour5.gif'),
        require('../assets/images/game-images/pets/cro1.gif'),
        require('../assets/images/game-images/pets/fia1.gif'),
        require('../assets/images/game-images/pets/gato1.gif'),
        require('../assets/images/game-images/pets/gato2.gif'),
        require('../assets/images/game-images/pets/gato3.gif'),
        require('../assets/images/game-images/pets/gato4.gif'),
        require('../assets/images/game-images/pets/gato5.gif'),
        require('../assets/images/game-images/pets/gato6.gif'),
        require('../assets/images/game-images/pets/gato7.gif'),
        require('../assets/images/game-images/pets/gray1.gif'),
        require('../assets/images/game-images/pets/gray2.gif'),
        require('../assets/images/game-images/pets/gray3.gif'),
        require('../assets/images/game-images/pets/jd1.gif'),
        require('../assets/images/game-images/pets/jig1.gif'),
        require('../assets/images/game-images/pets/julia1.gif'),
        require('../assets/images/game-images/pets/julia2.gif'),
        require('../assets/images/game-images/pets/mima1.gif'),
        require('../assets/images/game-images/pets/moralle1.gif'),
        require('../assets/images/game-images/pets/moralle2.gif'),
        require('../assets/images/game-images/pets/moralle3.gif'),
        require('../assets/images/game-images/pets/quail1.gif'),
        require('../assets/images/game-images/pets/quo1.gif'),
        require('../assets/images/game-images/pets/quo2.gif'),
        require('../assets/images/game-images/pets/quo3.gif'),
        require('../assets/images/game-images/pets/silk1.gif'),
        require('../assets/images/game-images/pets/silk2.gif'),
        require('../assets/images/game-images/pets/silk3.gif'),
        require('../assets/images/game-images/pets/slacky1.gif'),
        require('../assets/images/game-images/pets/slacky2.gif'),
        require('../assets/images/game-images/pets/splishy1.gif'),
        require('../assets/images/game-images/pets/splishy2.gif'),
        require('../assets/images/game-images/pets/splishy3.gif'),
        require('../assets/images/game-images/pets/splishy4.gif'),
        require('../assets/images/game-images/pets/splishy5.gif'),
        require('../assets/images/game-images/pets/splishy6.gif'),
        require('../assets/images/game-images/pets/splishy7.gif'),
        require('../assets/images/game-images/pets/splishy8.gif'),
        require('../assets/images/game-images/pets/splishy9.gif'),
        require('../assets/images/game-images/pets/splishy10.gif'),
        require('../assets/images/game-images/pets/tono1.gif'),
        require('../assets/images/game-images/pets/tono2.gif'),
        require('../assets/images/game-images/pets/tono3.gif'),
        require('../assets/images/game-images/pets/tpop1.gif'),
    ],
    "background": [
        require('../assets/images/game-images/window.png'),
        require('../assets/images/game-images/backgrounds/tono1.png'),
        require('../assets/images/game-images/backgrounds/tono2.png'),
        require('../assets/images/game-images/backgrounds/gato1.png'),
        require('../assets/images/game-images/backgrounds/jd1.png'),
        require('../assets/images/game-images/backgrounds/moralle1.png'),
        require('../assets/images/game-images/backgrounds/moralle2.png'),
        require('../assets/images/game-images/backgrounds/moralle3.png'),
        require('../assets/images/game-images/backgrounds/moralle4.png'),
        require('../assets/images/game-images/backgrounds/silk1.png'),
        require('../assets/images/game-images/backgrounds/silk2.png'),
        require('../assets/images/game-images/backgrounds/silk3.png'),
        require('../assets/images/game-images/backgrounds/splishy1.png'),
        require('../assets/images/game-images/backgrounds/splishy2.png'),
        require('../assets/images/game-images/backgrounds/splishy3.png'),
        require('../assets/images/game-images/backgrounds/tpop1.png'),
    ],
    "placeholderBackground": [
        require('../assets/images/game-images/window.png'),
    ],
    "yes": require('../assets/images/game-images/checkmark.png'),
    "no": require('../assets/images/game-images/x.png'),
    "shadow": require('../assets/images/game-images/shadow.png'),
    "backgroundMappings":[
        -1,
        -1,
        -1,
        26,
        28,
        29,
        30,
        30,
        35,
        36,
        37,
        38,
        39,
        40,
        48,
        49,
        52
    ] //here if necessary but i hope we can leave the backgrounds unlocked
    
}

export function shuffle() {
    const size = PetImages.egg.length;
    let unshuffled = [];
    for (let i = 0; i < size; i += 1) {
        unshuffled.push(i);
    }
    const shuffled = unshuffled.map(value => ({value, sort: Math.random() }))
                                .sort((a, b) => a.sort - b.sort)
                                .map(({value}) => value)
    return shuffled;
}